# Generated by Django 3.2 on 2025-07-20 10:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_training', models.BooleanField(default=False, verbose_name='是否正在训练')),
                ('current_epoch', models.IntegerField(default=0, verbose_name='当前轮数')),
                ('total_epochs', models.IntegerField(default=0, verbose_name='总轮数')),
                ('current_step', models.IntegerField(default=0, verbose_name='当前步数')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步数')),
                ('train_loss', models.FloatField(default=0.0, verbose_name='训练损失')),
                ('eval_loss', models.FloatField(default=0.0, verbose_name='评估损失')),
                ('eval_f1', models.FloatField(default=0.0, verbose_name='F1分数')),
                ('eval_accuracy', models.FloatField(default=0.0, verbose_name='准确率')),
                ('eval_recall', models.FloatField(default=0.0, verbose_name='召回率')),
                ('progress_percent', models.FloatField(default=0.0, verbose_name='进度百分比')),
                ('logs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='训练日志')),
                ('final_metrics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='最终指标')),
                ('hyperparameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='超参数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('should_stop', models.BooleanField(default=False, verbose_name='停止标志')),
                ('training_start_time', models.DateTimeField(blank=True, null=True, verbose_name='训练开始时间')),
                ('training_end_time', models.DateTimeField(blank=True, null=True, verbose_name='训练结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '训练状态',
                'verbose_name_plural': '训练状态',
                'db_table': 'training_status',
            },
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.TextField(verbose_name='分析结果'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.TextField(verbose_name='需要分析的字段'),
        ),
    ]
