# Generated by Django 3.2 on 2025-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_auto_20250720_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstatus',
            name='final_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='最终指标'),
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='hyperparameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='超参数'),
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='logs',
            field=models.JSONField(blank=True, default=list, verbose_name='训练日志'),
        ),
    ]
